name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19'

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Create test files
      run: |
        mkdir -p /tmp/source
        mkdir -p /tmp/destination
        echo "This is a test file" > /tmp/source/test_file.txt

    - name: Test rsync command
      run: |
        echo "Testing rsync"
        rsync -avz /tmp/source/ /tmp/destination/
        ls -l /tmp/destination/

    - name: Display deployment environment variables
      run: |
        echo "SERVER_USER=${{ secrets.SERVER_USER }}"
        echo "SERVER_IP=${{ secrets.SERVER_IP }}"
        echo "SERVER_SSH_PORT=${{ secrets.SERVER_SSH_PORT }}"

    - name: List deployment files
      run: |
        ls -la ./dice-game/
        ls -la ./server.js
        ls -la ./package.json
        ls -la ./package-lock.json

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_github_actions
        chmod 600 ~/.ssh/id_rsa_github_actions
        ssh-keyscan -p ${{ secrets.SERVER_SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Check SSH key permissions
      run: ls -l ~/.ssh/id_rsa_github_actions

    - name: Deploy source files to Server
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_rsa_github_actions -p $SERVER_SSH_PORT" --progress ./dice-game/ $SERVER_USER@$SERVER_IP:/var/www/biskit/client/
        rsync -avz -e "ssh -i ~/.ssh/id_rsa_github_actions -p $SERVER_SSH_PORT" --progress ./server.js $SERVER_USER@$SERVER_IP:/var/www/biskit/server/
        rsync -avz -e "ssh -i ~/.ssh/id_rsa_github_actions -p $SERVER_SSH_PORT" --progress ./package.json $SERVER_USER@$SERVER_IP:/var/www/biskit/server/
        rsync -avz -e "ssh -i ~/.ssh/id_rsa_github_actions -p $SERVER_SSH_PORT" --progress ./package-lock.json $SERVER_USER@$SERVER_IP:/var/www/biskit/server/
        ssh -i ~/.ssh/id_rsa_github_actions -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_IP "cd /var/www/biskit/client && npm install && npm run build"
        ssh -i ~/.ssh/id_rsa_github_actions -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_IP "cd /var/www/biskit/server && npm install"
        ssh -i ~/.ssh/id_rsa_github_actions -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_IP "pm2 restart biskit-server"
